# Generated by Django 5.0.3 on 2024-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_commodity_average_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='price_1_day_ago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='price_1_hour_ago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='price_7_days_ago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
