# Generated by Django 5.0.3 on 2024-03-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_commodity_price_1_day_ago_commodity_price_1_hour_ago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_name', to='tracker.commodityname'),
        ),
    ]
