# Generated by Django 4.2.1 on 2024-03-16 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_commodity_price_1_day_ago_commodity_price_1_hour_ago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='price_1_day_ago',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='price_1_hour_ago',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='price_7_days_ago',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='time',
        ),
        migrations.AddField(
            model_name='commodity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.commodity')),
            ],
        ),
    ]
