# Generated by Django 5.0.3 on 2024-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_commodityname_alter_commodity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='symbol',
        ),
        migrations.AddField(
            model_name='commodityname',
            name='symbol',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodityname',
            name='tradeable',
            field=models.BooleanField(default=False),
        ),
    ]
