# Generated by Django 4.2.1 on 2024-03-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_commodity_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='percentage_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
