# Generated by Django 5.0.3 on 2024-03-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_commodity_symbol_commodityname_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityname',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
